language: python

python:
  - "2.7"

sudo: required  # Required for docker
services:
  - docker
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-matplotlib  # For runbot badges

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/vauxoo-dev/maintainer-quality-tools.git -b master-oca-t2d-compatibility ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install -r requirements.txt
  
  # odoo-extra has a bunch of v9 modules which aren't compatible, remove them
  - (cd ${HOME}/dependencies/odoo-extra; rm -rf $(ls | grep -v runbot$))
  
  # odoo version 9.0 compatibility
  - find ${HOME}/dependencies/odoo-extra/runbot -name res_config_view.xml -exec sed -i 's/base.menu_config/base.menu_administration/g' {} \;

  # Disabling matplotlib by https://github.com/travis-ci/travis-ci/issues/4948
  - find ${HOME}/dependencies/odoo-extra/runbot -name runbot.py -exec sed -i  '/from matplotlib.font_manager import FontProperties/d' {} \;
  - find ${HOME}/dependencies/odoo-extra/runbot -name runbot.py -exec sed -i  '/from matplotlib.textpath import TextToPath/d' {} \;
  - find ${HOME}/dependencies/odoo-extra/runbot -name __openerp__.py -exec sed -i  '/'matplotlib'/d' {} \;

  # Disabling test_crawl (native runbot fail)
  - find ${HOME} -name __init__.py -exec sed -i  "/import test_crawl/d" {} \;
  
  # Download docker image required
  - if [ "${TESTS}" == "1"  ]; then docker pull vauxoo/odoo-80-image-shippable-auto; fi

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
